# Try to find the PHYSFS library
#  PHYSFS_FOUND - system has PHYSFS
#  PHYSFS_INCLUDE_DIR - the PHYSFS include directory
#  PHYSFS_LIBRARY - the PHYSFS library

FIND_PATH(WININET_INCLUDE_DIR wininet.h PATH_SUFFIXES wininet)
SET(_WININET_STATIC_LIBS libwininet.a)
SET(_WININET_SHARED_LIBS libwininet.dll.a wininet)
IF(USE_STATIC_LIBS)
    FIND_LIBRARY(WININET_LIBRARY NAMES ${_WININET_STATIC_LIBS} ${_WININET_SHARED_LIBS})
ELSE()
    FIND_LIBRARY(WININET_LIBRARY NAMES ${_WININET_SHARED_LIBS} ${_WININET_STATIC_LIBS})
ENDIF()
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(WININET DEFAULT_MSG WININET_LIBRARY WININET_INCLUDE_DIR)
MARK_AS_ADVANCED(WININET_LIBRARY WININET_INCLUDE_DIR)